#!/bin/sh

ln -sf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
hwclock --systohc
sed -i '178s/.//' /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >> /etc/locale.conf
echo "arch" >> /etc/hostname
echo "127.0.0.1 localhost" >> /etc/hosts
echo "::1       localhost" >> /etc/hosts
echo "127.0.1.1 arch.localdomain arch" >> /etc/hosts

pacman -S grub grub-btrfs efibootmgr networkmanager network-manager-applet dialog wpa_supplicant mtools reflector linux-headers inetutils bluez bluez-utils alsa alsa-utils pipewire pipewire-alsa pipewire-pulse rsync acpi acpi_call sof-firmware acpid nvidia nvidia-utils nvidia-settings xdg-user-dirs xdg-utils xorg wget sxiv unrar unzip man-db man-pages sxhkd stow pavucontrol feh mpv jq btop alacritty dunst curl nemo zathura zathura-pdf-mupdf zip sddm polkit firefox noto-fonts-cjk noto-fonts noto-fonts-emoji ttf-linux-libertine ttf-dejavu p7zip firefox

grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB #change the directory to /boot/efi is you mounted the EFI partition at /boot/efi

grub-mkconfig -o /boot/grub/grub.cfg

systemctl enable NetworkManager
systemctl enable bluetooth
systemctl enable reflector.timer
systemctl enable fstrim.timer
systemctl enable acpid
systemctl enable sddm 

useradd -m -g wheel tinkerbells
echo tinkerbells:password | chpasswd
echo "%wheel ALL=(ALL:ALL) ALL" >> /etc/sudoers
printf "\e[1;32mDone! Type exit, umount -R and reboot.\e[0m"
