#!/bin/sh

# Setup locale, time and hosts params
ln -sf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
hwclock --systohc
sed -i "s/#en_US.UTF-8/en_US.UTF-8/" /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >>/etc/locale.conf
echo "arch" >>/etc/hostname
echo "127.0.0.1 localhost" >>/etc/hosts
echo "::1       localhost" >>/etc/hosts
echo "127.0.1.1 arch.localdomain arch" >>/etc/hosts

# Install necessary packages
pacman -S grub grub-btrfs btrfs-progs efibootmgr networkmanager network-manager-applet dialog wpa_supplicant mtools reflector linux-headers inetutils bluez bluez-utils alsa-utils pipewire pipewire-alsa pipewire-pulse rsync acpi acpi_call sof-firmware acpid xdg-utils man-db man-pages polkit xorg xorg-xinit gd

# Install grub
# pacman -S grub grub-btrfs
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
grub-mkconfig -o /boot/grub/grub.cfg

# Install systemd-boot
# bootctl --path=/boot install
# echo "default arch-*" >> /boot/loader/loader.conf
# echo "timeout 0" >> /boot/loader/loader.conf
# echo "title Arch Linux" >> /boot/loader/entries/arch.conf
# echo "linux /vmlinuz-linux" >> /boot/loader/entries/arch.conf
# echo "initrd /initramfs-linux.img" >> /boot/loader/entries/arch.conf
# echo "initrd /amd-ucode.img" >> /boot/loader/entries/arch.conf
# echo "options root=UUID=UUID-HERE rootflags=subvol=@ rw" >> /boot/loader/entries/arch.conf

# Enable systemd services
systemctl enable NetworkManager
systemctl enable bluetooth
systemctl enable reflector.timer
systemctl enable fstrim.timer
systemctl enable acpid

# Setup user
useradd -m -g wheel user
echo user:password | chpasswd
echo "%wheel ALL=(ALL:ALL) ALL" >>/etc/sudoers

# Update mkinicpio with btrfs module
sed -i "7s/MODULES=()/MODULES=(btrfs)/" /etc/mkinitcpio.conf
mkinitcpio -p linux

printf "\e[1;32mDone! Type exit, umount -R and reboot.\e[0m"
