#!/bin/sh

# Install paru
git clone https://aur.archlinux.org/paru && cd paru && makepkg -si

# Setup reflector params
reflector -c Russia -c Belarus -c Ukraine -c Finland -c Poland -a 12 -p https -p http --sort rate -l 5 --save /etc/pacman.d/mirrorlist
paru

# Change grub config to load system immediately
sudo sed -i "s/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/" /etc/default/grub
sudo grub-mkconfig -o /boot/grub/grub.cfg   

# Install all necessary packages
paru -S xidlehook calibre discord telegram-desktop timeshift picom-git lf redshift ncmpcpp mpd mpc mpv ueberzug pamixer qbittorrent shellcheck codespell openresolv envycontrol speedtest-cli tty-clock-git zramd resolvconf wireguard-tools code npm nodejs autoconf autoconf-archive pkg-config imlib2 libbsd brillo papirus-icon-theme catppuccin-gtk-theme rofi rofi-greenclip rofi-calc devour xclip xsel xdotool brave-bin jackett yt-dlp mpd-notification-git poppler atool ly farge xcolor bat mullvad-vpn-bin auto-cpufreq bc scrot wget sxiv sxhkd stow pavucontrol feh jq btop alacritty dunst curl nemo zathura zathura-pdf-mupdf zip noto-fonts-cjk noto-fonts noto-fonts-emoji ttf-linux-libertine ttf-dejavu


# Download wallpapers
git clone https://github.com/Tinkerbells/wallpapers.git ~/Pictures/wallpapers

# Installing brillo right way
paru -R brillo
git clone https://github.com/CameronNemo/brillo.git && cd brillo && make && sudo make install.setgid 

# Disable nvidia graphics 
sudo envycontrol -s integrated 

# Setup conifg files
sudo cp ./configs/auto-cpufreq.conf /etc/  
sudo cp ./configs/30-touchpad.conf /etc/X11/xorg.conf.d/ 

# Setup udev rules
sudo cp ./udev-rules/* /etc/udev/rules.d/ 
sudo udevadm control --reload-rules 

# Enable systemd services
sudo systemctl enable --now zramd
sudo systemctl enable auto-cpufreq
sudo systemctl enable cronie
sudo systemctl enable ly 
sudo systemctl enable mpd
systemctl --user enable pipewire
systemctl --user enable mpd-notification


# Change npm prefix to local
npm config set prefix ~/.local

# Remove unnecessary files
rm -rf ./brillo ./paru

mkdir $HOME/Pictures/screenshots && mkdir $HOME/Projects

printf "\e[1;32mDone!\e[0m"
